# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gmt_bayes_par_negll <- function(pars, max_titers, min_titers, prior_mean_mean, prior_mean_sd, prior_sd_shape, prior_sd_scale) {
    .Call('_meantiter_gmt_bayes_par_negll', PACKAGE = 'meantiter', pars, max_titers, min_titers, prior_mean_mean, prior_mean_sd, prior_sd_shape, prior_sd_scale)
}

