# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate log likelihood of single fitted HI titer
#' 
#' This is the base function for performing a maximum likelihood calculation for a 
#' single fitted HI titer given upper and lower limits of the measured value.
#'
#' @param max_titer The upper bound of the measured titer.
#' @param min_titer The lower bound of the measured titer.
#' @param pred_titer The predicted titer.
#' @param error_sd The standard deviation of the error.
#'
#' @details This function simply calculates to log likelihood of a predicted measurement 
#' given the upper and lower bounds of the measurement, the main assumption being that the 
#' associated error is normally distributed.
#'
#' @return Returns the log-likelihood of the measured titer given the measured titer 
#' bounds and error standard deviation supplied.
NULL

#' Calculate the total negative log-likelihood of a mean titer
#' 
#' This is a base function to sum the total _negative_ log likelihood of a mean titer.
#' 
#' @param max_titers Numeric vector of the upper bounds of the measured titers.
#' @param min_titers Numeric vector of the lower bounds of the measured titers.
#' @param predicted_mean The predicted mean titer.
#' @param titer_sd The expected standard deviation of titers.
#' 
#' @details This function calculates the total negative log-likelihood of a predicted mean 
#' titer given a set of titers. The main assumption is that both measurement error and 
#' titer variation are normally distributed. Note that the argument \code{titer_sd} is the 
#' total expected standard deviation of the titer set, i.e. measurement error plus titer 
#' variation.
#' 
calc_mean_titer_negll <- function(predicted_mean, max_titers, min_titers, titer_sd) {
    .Call('_meantiter_calc_mean_titer_negll', PACKAGE = 'meantiter', predicted_mean, max_titers, min_titers, titer_sd)
}

calc_mean_titer_negll_by_par <- function(pars, max_titers, min_titers, titer_sd) {
    .Call('_meantiter_calc_mean_titer_negll_by_par', PACKAGE = 'meantiter', pars, max_titers, min_titers, titer_sd)
}

calc_mean_titer_ci_by_par <- function(pars, max_titers, min_titers, titer_sd, target_negll) {
    .Call('_meantiter_calc_mean_titer_ci_by_par', PACKAGE = 'meantiter', pars, max_titers, min_titers, titer_sd, target_negll)
}

